name = "studium-api"
main = "index.js"
compatibility_date = "2024-12-01"

[vars]
MOODLE_URL = "https://campus.ucalp.edu.ar"
AI_MODEL = "google/gemini-3-flash-preview"
GOOGLE_CLIENT_ID = "31981905435-gmek9jqno3p2o91pkmsfucl2jv8kpmb9.apps.googleusercontent.com"
ALLOWED_ORIGIN = "https://studium-6hw.pages.dev"

# Set secrets via CLI:
# wrangler secret put OPENROUTER_API_KEY
# wrangler secret put GOOGLE_CLIENT_SECRET
